# Generated by Django 2.1 on 2018-09-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Тип упаковки')),
                ('with_NO_NDS', models.IntegerField(verbose_name='Цена без НДС')),
                ('with_NDS', models.IntegerField(verbose_name='Цена с НДС')),
            ],
        ),
    ]
