# Generated by Django 2.1 on 2018-09-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0002_footerinfo_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
    ]
