# Generated by Django 2.1 on 2018-09-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0003_auto_20180912_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerinfo',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='footerinfo',
            name='value',
            field=models.CharField(max_length=20, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='quality',
            name='value',
            field=models.CharField(max_length=20, verbose_name='Значение'),
        ),
    ]
