# Generated by Django 2.1 on 2018-09-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0004_auto_20180912_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerinfo',
            name='value',
            field=models.CharField(max_length=50, verbose_name='Значение'),
        ),
    ]
