# Generated by Django 2.1 on 2018-09-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0006_messegeform'),
    ]

    operations = [
        migrations.AddField(
            model_name='messegeform',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
