# Generated by Django 2.1 on 2018-09-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0007_messegeform_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messegeform',
            name='datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата/Время'),
        ),
    ]
