# Generated by Django 2.1 on 2018-09-12 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0009_auto_20180913_0126'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessegeForm',
            new_name='MessageForm',
        ),
    ]
