# Generated by Django 2.1 on 2018-09-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0010_auto_20180913_0130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageForm',
            new_name='MessageFormModel',
        ),
    ]
