# Generated by Django 2.1 on 2018-09-15 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0011_auto_20180915_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerinfo',
            options={'verbose_name': 'Футер', 'verbose_name_plural': 'Футер'},
        ),
        migrations.AlterModelOptions(
            name='messageformmodel',
            options={'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Цены', 'verbose_name_plural': 'Цены'},
        ),
        migrations.AlterModelOptions(
            name='quality',
            options={'verbose_name': 'Качество', 'verbose_name_plural': 'Качество'},
        ),
    ]
