# Generated by Django 2.1 on 2018-09-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainPage', '0012_auto_20180915_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerEmailBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('value', models.CharField(max_length=50, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Ящик куда падают заявки',
                'verbose_name_plural': 'Ящик куда падают заявки',
            },
        ),
    ]
